name: Setup Node.js
description: Set up Node.js and dependencies

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: corepack enable
    - run: pnpm install
